# Copyright 2022 NetApp, Inc. All Rights Reserved.
# Licensed under the Apache License, Version 2.0.

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: beegfs-client
  name: beegfs-client
  namespace: beegfs-csi

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: beegfs-client
  name: beegfs-client
  namespace: beegfs-csi
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: beegfs-client
  name: beegfs-client
  namespace: beegfs-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: beegfs-client
subjects:
- kind: ServiceAccount
  name: beegfs-client
userNames:
- system:serviceaccount:beegfs-csi:beegfs-client

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: beegfs-client
  name: beegfs-client
  namespace: beegfs-csi
spec:
  selector:
    matchLabels:
      app: beegfs-client
  template:
    metadata:
      labels:
        app: beegfs-client
    spec:
      serviceAccount: beegfs-client
      serviceAccountName: beegfs-client
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/beegfs-csi/beegfs-client:latest
          name: beegfs-client
          imagePullPolicy: Always
          command: ["/sbin/init"]
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "/usr/local/sbin/poststart.sh"]
            preStop:
              exec:
                command: ["/bin/sh", "-c", "systemctl stop beegfs-client beegfs-helperd"]
          securityContext:
            privileged: true
          volumeMounts:
            # This mount allows us to put files and executables where the CSI driver can access them.
            - mountPath: /plugin/client
              name: plugin-client-dir
      ports:
            - containerPort: 8006
              hostPort: 8006
      hostNetwork: true
      volumes:
        - name: plugin-client-dir
          hostPath:
            type: DirectoryOrCreate
            path: /var/lib/kubelet/plugins/beegfs.csi.netapp.com/client
