kind: Service
apiVersion: v1
metadata:
  name: csi-beegfs-snapshotter
  labels:
    app: csi-beegfs-snapshotter
spec:
  selector:
    app: csi-beegfs-snapshotter
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-beegfs-snapshotter
spec:
  serviceName: "csi-beegfs-snapshotter"
  replicas: 1
  selector:
    matchLabels:
      app: csi-beegfs-snapshotter
  template:
    metadata:
      labels:
        app: csi-beegfs-snapshotter
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-beegfsplugin
            topologyKey: kubernetes.io/hostname
      serviceAccount: csi-snapshotter
      containers:
        - name: csi-snapshotter
          image: k8scsi/csi-snapshotter:v1.2.0
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-beegfs
            type: DirectoryOrCreate
          name: socket-dir
