# Copyright 2021 NetApp, Inc. All Rights Reserved.
# Licensed under the Apache License, Version 2.0.

# TODO(webere, A219): Document the use of or remove this file.

kind: BeegfsDriver
apiVersion: beegfs.csi.netapp.com/v1
metadata:
  name: csi-beegfs-cr  # CR must have this name.
spec:
  containerImageOverrides:
    beegfsCsiDriver:
      image: docker.repo.eng.netapp.com/globalcicd/apheleia/beegfs-csi-driver
      tag: master
    csiNodeDriverRegistrar:
      image: docker.repo.eng.netapp.com/sig-storage/csi-node-driver-registrar
    csiProvisioner:
      image: docker.repo.eng.netapp.com/sig-storage/csi-provisioner
    livenessProbe:
      image: docker.repo.eng.netapp.com/sig-storage/livenessprobe
  logLevel: 5
