# Copyright 2021 NetApp, Inc. All Rights Reserved.
# Licensed under the Apache License, Version 2.0.

# This file is ignored by default. Move it to an overlay and add a reference to it in
# overlay-<something>/kustomization.yaml to enable it.

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-beegfs-controller
spec:
  template:
    spec:
      containers:
        - name: beegfs
          env:
            - name: LOG_LEVEL
              value: '5'  # Fill in with an appropriate value.

---

kind: StatefulSet
apiVersion: apps/v1
metadata:
 name: csi-beegfs-controller
spec:
 template:
   spec:
     containers:
       - name: csi-provisioner
         env:
           - name: LOG_LEVEL
             value: '5'  # Fill in with an appropriate value.

---

kind: DaemonSet
apiVersion: apps/v1
metadata:
 name: csi-beegfs-node
spec:
 template:
   spec:
     containers:
       - name: beegfs
         env:
           - name: LOG_LEVEL
             value: '5'  # Fill in with an appropriate value.

---

kind: DaemonSet
apiVersion: apps/v1
metadata:
 name: csi-beegfs-node
spec:
 template:
   spec:
     containers:
       - name: node-driver-registrar
         env:
           - name: LOG_LEVEL
             value:  '5'  # Fill in with an appropriate value.
