# Modifications Copyright 2021 NetApp, Inc. All Rights Reserved.
# Licensed under the Apache License, Version 2.0.

# WARNING: this is only for testing purposes. Do not install in a production
# cluster.
#
# This exposes the beegfs's Unix domain csi.sock as a TCP port to the
# outside world. The mapping from Unix domain socket to TCP is done
# by socat.
#
# This is useful for testing with csi-sanity or csc.

# TODO(webere, A94): Get csi-beegfs-socat working with the new driver deployment.
# csi-driver-hostpath uses this pod for csc and/or sanity testing. However, all of the pods/services in the
# csi-driver-hostpath deployment colocate on one node and share one unix socket.

apiVersion: v1
kind: Service
metadata:
  name: beegfs-service
spec:
  type: NodePort
  selector:
    app: csi-beegfs-socat
  ports:
  - port: 10000 # fixed port inside the pod, dynamically allocated port outside
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-beegfs-socat
spec:
  serviceName: "csi-beegfs-socat"
  replicas: 1
  selector:
    matchLabels:
      app: csi-beegfs-socat
  template:
    metadata:
      labels:
        app: csi-beegfs-socat
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-beegfs-controller
            topologyKey: kubernetes.io/hostname
      containers:
        - name: socat
          image: socat
          args:
            - tcp-listen:10000,fork,reuseaddr
            - unix-connect:/csi/csi.sock
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-beegfs
            type: DirectoryOrCreate
          name: socket-dir
