# Copyright 2021 NetApp, Inc. All Rights Reserved.
# Licensed under the Apache License, Version 2.0.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - csi-beegfs-controller.yaml
  - csi-beegfs-controller-rbac.yaml
  - csi-beegfs-driverinfo.yaml
  - csi-beegfs-node.yaml
