# Copyright 2021 NetApp, Inc. All Rights Reserved.
# Licensed under the Apache License, Version 2.0.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - csi-beegfs-controller.yaml
  - csi-beegfs-controller-rbac.yaml
  - csi-beegfs-driverinfo.yaml
  - csi-beegfs-node.yaml
configMapGenerator:
  # Kustomize will append a hash of the ConfigMap data to this name because it is considered "bad practice" to change
  # the data held in a live ConfigMap. Kustomize will also change all references to this ConfigMap to include the hash.
  # It will do this any time a "kubectl apply -k" is used in combination with changed config data, so StatefulSets,
  # Deployments, etc. are updated and know about the latest changes.
  - name: csi-beegfs-config
    files:
      - csi-beegfs-config.yaml
