# Copyright 2022 NetApp, Inc. All Rights Reserved.
# Licensed under the Apache License, Version 2.0.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: beegfs-csi  # Modify this to deploy to a different namespace.
bases:
  - ../../versions/latest  # Modify this to select a specific Kubernetes version.
resources:
  - namespace.yaml
patchesStrategicMerge:
  # See ../examples/patches for additional patch ideas.
  - patches/node-affinity.yaml
  # Uncomment the following line and edit the referenced file to adjust the driver resource limits
  # - patches/container-resources.yaml
configMapGenerator:
  # Kustomize will append a hash of the ConfigMap data to this name because it is considered "bad practice" to change
  # the data held in a live ConfigMap. Kustomize will also change all references to this ConfigMap to include the hash.
  # It will do this any time a "kubectl apply -k" is used in combination with changed config data, so StatefulSets,
  # Deployments, etc. are updated and know about the latest changes.
  - name: csi-beegfs-config
    files:
      - csi-beegfs-config.yaml
secretGenerator:
  # Kustomize will append a hash of the Secret data to this name because it is considered "bad practice" to change
  # the data held in a live Secret. Kustomize will also change all references to this Secret to include the hash.
  # It will do this any time a "kubectl apply -k" is used in combination with changed config data, so StatefulSets,
  # Deployments, etc. are updated and know about the latest changes.
  - name: csi-beegfs-connauth
    files:
      - csi-beegfs-connauth.yaml

# Uncomment this section and fill it in as appropriate for air-gapped deployments or deployments that require custom
# container names (e.g. when a private registry is used). The default image names MAY change in a future driver update.
# Check /deploy/k8s/bases for updated names in the case of a failing upgrade.
# images:
#   - name: docker.io/netapp/beegfs-csi-driver
#     newName:
#     newTag:
#   - name: k8s.gcr.io/sig-storage/csi-provisioner
#     newName:
#     newTag:
#   - name: k8s.gcr.io/sig-storage/livenessprobe
#     newName:
#     newTag:
#   - name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
#     newName:
#     newTag:
