apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-beegfs-static-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: csi-beegfs-static-pv
