apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-01-scratch
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests: 
      storage: 100Gi
  storageClassName: beegfs-scratch