apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-net-static-pv
spec:
  capacity: 
    storage: 150Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: beegfs.csi.netapp.com
    volumeHandle: beegfs://10.113.72.217/datasets/imagenet
    volumeAttributes:
      beegfsConf/sysMgmtdHost: 10.113.72.217
      volDirBasePath: datasets/imagenet 
