apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-beegfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-beegfs-sc  # defined in csi-sc.yaml
