kind: Pod
apiVersion: v1
metadata:
  name: csi-beegfs-app
spec:
  containers:
    - name: csi-beegfs-app
      image: alpine:latest
      volumeMounts:
      - mountPath: "/data"
        name: csi-beegfs-volume
      # Create a file with the pod's UUID as its name to demonstrate the ability to write to BeeGFS.
      # Sleep to demonstrate the container runs successfully.
      command: [ "ash", "-c", 'touch "/data/touched-by-${POD_UUID}" && sleep 10000']
      env:
        - name: POD_UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
  volumes:
    - name: csi-beegfs-volume
      persistentVolumeClaim:
        claimName: csi-beegfs-pvc  # defined in csi-pvc.yaml
