# Copyright 2021 NetApp, Inc. All Rights Reserved.
# Licensed under the Apache License, Version 2.0.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-beegfs-dyn-sc
provisioner: beegfs.csi.netapp.com
parameters:
  # Replace "localhost" with the IP address or hostname of the BeeGFS management daemon.
  sysMgmtdHost: localhost
  # Replace "name" with a unique k8s cluster name to prevent multiple k8s clusters from dynamically provisioning volumes at the same BeeGFS path.
  volDirBasePath: k8s/name/dyn
  # Optionally configure the default stripePattern parameters.
  # stripePattern/storagePoolID: "1"
  # stripePattern/chunkSize: 512k
  # stripePattern/numTargets: "4"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: false
