apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-beegfs-static-ro-pvc
spec:
  accessModes:
  - ReadOnlyMany
  # spec.resources[storage] is required (see the comment in static-ro-pv.yaml).
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: csi-beegfs-static-ro-pv
