apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-net-static
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
  storageClassName: ""
  volumeName: image-net-static-pv