# Copyright 2021 NetApp, Inc. All Rights Reserved.
# Licensed under the Apache License, Version 2.0.

# This is a fairly complicated csi-beegfs-connauth.yaml representing multiple file systems that each require a
# connAuthFile for access. See ../../docs/deployment.md for complete instructions on how to use this file.

- sysMgmtdHost: some.specific.file.system
  connAuth: some-secret
- sysMgmtdHost: some.other.specific.file.system
  connAuth: some-other-secret
